version: "3"
services:
  frontend:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./frontend
    image: shjeon97/exam-world-frontend:1.0.0
    container_name: exam-world-frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"

  backend:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./backend
    image: shjeon97/exam-world-backend:1.0.0
    container_name: exam-world-backend
    volumes:
      - /main/public/exam-world/upload:/public/upload
    env_file:
      - ./backend/.env.prod
    ports:
      - "4000:4000"
