version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    image: shjeon97/exam-world-frontend:1.0.0
    container_name: exam-world-frontend
    env_file:
      - ./frontend/.env

  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    image: shjeon97/exam-world-backend:1.0.0
    container_name: exam-world-backend
    env_file:
      - ./backend/.env.prod

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    image: shjeon97/exam-world-nginx:1.0.0
    container_name: exam-world-nginx
    ports:
      - "80:80"

 