version: "3"
services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./data:/var/lib/postgresql/data
