name: Node.js CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }} backend
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./backend/package-lock.json"

      - run: npm install --force
        working-directory: backend

      - name: Create .env.test file
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env.test
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env.test
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env.test
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env.test
          echo "PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}" >> .env.test
          echo "PORT=${{ secrets.PORT }}" >> .env.test
          echo "SERVER_ADDRESS=${{ secrets.SERVER_ADDRESS }}" >> .env.test
        working-directory: backend

      - run: npm run test:e2e
        working-directory: backend
